---
- hosts: all
  become: yes
  tasks:
      - name: Generating RSA key for mgr
        user: name=root generate_ssh_key=yes ssh_key_bits=2048

- hosts: mgr
  become: yes
  tasks:
      - name: Install ansible.
        apt: name={{ item }} state=present update_cache=yes
        with_items:
            - ansible
      - name: copy necessary items
        script: ansible.sh
